#!/bin/zsh

typeset -A abbreviations
abbreviations=(
    "letter" "char"
    "frequency" "freq"
    "character" "char"
    "compare" "cmp"
    "duplicates" "dupes"
    "duplicate" "dupe"
    "strings" "strs"
    "string" "str"
    "adjacent" "adj"
    "average" "avg"
    "number" "num"
    "numbers" "nums"
    "value" "val"
    "values" "vals"
    "divisible" "div"
    "temperature" "temp"
)

checkAbbreviations() {
    local t=$1
    if [[ -n ${abbreviations[$t]} ]]; then
        echo ${abbreviations[$t]}
    else
        echo $t
    fi
}

if [[ $# -ne 1 ]]; then
    echo "Usage: $0 \"14. Longest Common Prefix\"" >&2
    exit 1
fi

t=$1

# Extract number and pad to 4 digits
num=$(printf "%04d" ${t%%.*})
ret="${num}"

# Split title into words
words=(${(z)t})
for (( i=2; i<=$#words; i++ )); do
    word=${(L)words[$i]}
    word=$(checkAbbreviations $word)
    ret="${ret}-${word}"
done

ret="${ret}.cpp"
echo $ret

# Create the file with a basic template
echo "#include <bits/stdc++.h>" > $ret
echo "using namespace std;" >> $ret
echo >> $ret

exit 0
